### PR TITLE
Sort modems by path

### PR DESCRIPTION
**Pull request by monich**
This guarantees the order in which `QOfonoManager::modems()` returns modem paths. If we have more than one modem (say, `/ril_0` and `/ril_1`) the first one is guaranteed to be `/ril_0`, which is good for compatibility.

### CODE REVIEW

**Comment by amccarthy** [comment]
LGTM. It doesn't guarantee, for example, that /ril_0 will always point to the same hardware device unless ofono already guarantees that.

**Comment by lpotter** [comment]
What about when phonesim is present? Which is one reason why the crap sort was there in the first place.

**Comment by amccarthy** [comment]
The phonesim sort doesn't always work. The phonesim modem path is defined by the group in /etc/ofono/phonesim.conf. Currently my device has modems paths /PhoneSim1 /PhoneSim2 and /ril_0, which don't match current test.

**Comment by monich** [comment]
Right, let me check what it does to the unit tests

**Comment by monich** [comment]
Fixed one test failure (https://github.com/nemomobile/libqofono/pull/84) but it wasn't related to this change. And it shouldn't have affected tests in the first place, because there's only one `/phonesim` modem in the test environment.

And yes, ofono on its part has to guarantee that modems are named consistently.

**Pull request merged**
